baseURL = "https://mayurhulke.com/"
languageCode = "en-us"
title = "Mayur"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Mayur"
  description = "Personal blog for AI, Robotics, and Computer Vision"
  keywords = ["Blog", "AI", "Robotics", "Computer Vision", "Deep RL"]
  author = "Mayur Hulke"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  mainSections = ["posts", "papers", "projects", "books", "thoughts"]

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true
  
  # Custom CSS
  customCSS = ["css/custom.css"]
  
  # Math support
  math = true

[params.homeInfoParams]
  Title = "👋 Hey, it's Mayur"
  Content = """
  Building Physical Intelligence for Real-World Robots 🤖. I'm a Staff AI & Robotics Engineer specializing in Multi-agent Vision Language Action (VLA) systems, with a background in Advanced Robotics & AI from Bristol University and experience at Bristol Robotics Lab. I focus on developing intelligent systems that bridge the gap between vision, language, and robotic actions for general-purpose robotic manipulators.
  """

[[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@LetsTalkWithRobots"

[[params.socialIcons]]
  name = "x"
  url = "https://twitter.com/LetstalkRobots"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/themayurhulk"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mayurhulke/"

[[params.socialIcons]]
  name = "reddit"
  url = "https://www.reddit.com/user/LetsTalkWithRobots/"

[[params.socialIcons]]
  name = "link"
  url = "https://www.letstalkwithrobots.com/"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 15
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 50

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = false
  style = "monokai" 

[markup.goldmark.renderer]
  unsafe = true  # Allow raw HTML in markdown files

# Ignore specific warnings
ignoreLogs = ['warning-goldmark-raw-html'] 