baseURL = "https://mayurhulke.github.io/"
languageCode = "en-us"
title = "Mayur"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Mayur"
  description = "Personal blog for AI, Robotics, and Computer Vision"
  keywords = ["Blog", "AI", "Robotics", "Computer Vision", "Deep RL"]
  author = "Mayur Hulke"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  mainSections = ["posts", "papers", "projects", "books", "thoughts"]

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true
  
  # Custom CSS
  customCSS = ["css/custom.css"]
  
  # Math support
  math = true

[params.homeInfoParams]
  Title = "👋 Welcome to Mayur's Blog"
  Content = """
  Hi, this is Mayur. I'm documenting my learning notes & projects in this blog. I love building robots 🤖 been doing so since I was 14 (robowars used to be my Fav competition and won 30+ National robotics competitions growing up) 🏆

  Now I'm a Staff Robotics & Computer Vision engineer from London, England, working with big boys doing serious stuff I guess 😳
  
  I have a thing for deep ideas 💭 and trying to find the obvious truths around our existence (it's definitely harder than it sounds). During my limited free time, I enjoy getting lost in them and for some reason I enjoy reading books on long train journeys 🚆.
  """

[[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@LetsTalkWithRobots"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/MayurHulke"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/LetstalkRobots"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/themayurhulk"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/mayurhulke/"

[[params.socialIcons]]
  name = "link"
  url = "https://www.letstalkwithrobots.com/"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 15
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 50

[markup.highlight]
  noClasses = false
  codeFences = true
  guessSyntax = true
  lineNos = false
  style = "monokai" 

[markup.goldmark.renderer]
  unsafe = true  # Allow raw HTML in markdown files

# Ignore specific warnings
ignoreLogs = ['warning-goldmark-raw-html'] 